version: 2
before:
  hooks:
    - go test ./...
builds:
  - id: qordle
    binary: qordle
    goos:
      - linux
      - darwin
    main: ./cmd/qordle
    ldflags:
      - -s -w -X {{.ModulePath}}.buildVersion={{.Version}} -X {{.ModulePath}}.buildCommit={{.ShortCommit}} -X {{.ModulePath}}.buildTime={{.Date}} -X {{.ModulePath}}.buildBuilder=goreleaser
  - id: qordled
    binary: qordled
    goos:
      - linux
      - darwin
    main: ./cmd/qordled
    ldflags:
      - -s -w -X {{.ModulePath}}.buildVersion={{.Version}} -X {{.ModulePath}}.buildCommit={{.ShortCommit}} -X {{.ModulePath}}.buildTime={{.Date}} -X {{.ModulePath}}.buildBuilder=goreleaser
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
announce:
  skip: true

homebrew_casks:
  - name: qordle
    homepage: https://github.com/bzimmer/qordle
    description: Wordle problem solver
    license: MIT
    commit_author:
      name: bzimmer
      email: bzimmer@ziclix.com
    repository:
      owner: bzimmer
      name: homebrew-tap
    skip_upload: auto
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ma"]
          end
  - name: qordled
    homepage: https://github.com/bzimmer/qordle
    description: Wordle problem solver daemon
    license: MIT
    commit_author:
      name: bzimmer
      email: bzimmer@ziclix.com
    repository:
      owner: bzimmer
      name: homebrew-tap
    skip_upload: auto
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ma"]
          end
