# https://taskfile.dev

version: '3'

includes:
  build: ./Taskfile-build.yml

dotenv: [".clean.env"]

tasks:
  default:
    cmds:
      - task -l

  build:
    desc: Build all binaries
    cmds:
      - task: build:build

  test:
    desc: Run all tests
    cmds:
      - task: build:test

  qordled:
    desc: Run qordled
    deps: [build]
    env:
      BASE_URL: http://localhost:8091/qordle
    cmds:
      - "{{.DIST}}/qordled --port 8091"

  hyperfine:
    desc: Run hyperfine
    deps: [build]
    vars:
      binaries:
        "{{.DIST}}/qordle,/opt/homebrew/bin/qordle"
      options:
        -S -w solutions -w possible
      secrets:
        mound board brain lills qwert 12345
    cmds:
      - hyperfine -N -w 3 --runs=100 -L binary {{.binaries}} "{binary} play {{.options}} {{.secrets}}"

  regression:
    desc: Run regression test
    deps: [build]
    cmds:
      - "{{.ROOT_DIR}}/bin/regression.zsh {{.CLI_ARGS}}"
      - "{{.ROOT_DIR}}/bin/analyze.zsh"
