# https://taskfile.dev

version: '3'

dotenv: [".clean.env"]

vars:
  CWD:
    sh: git rev-parse --show-toplevel
  APP:
    sh: basename $PWD
  PKG:
    github.com/bzimmer/{{.APP}}
  DIST:
    "{{.CWD}}/dist"
  COMMIT:
    sh: git rev-parse --short HEAD

tasks:
  default:
    cmds:
      - task: build

  dist:
    desc: Create dist directory
    cmds:
      - mkdir -p {{.DIST}}

  test:
    desc: Run tests
    deps: [dist]
    cmds:
      # https://github.com/golang/go/issues/49138
      - go test {{.CLI_ARGS}} -race -count=1 -covermode atomic -coverprofile {{.DIST}}/coverage.txt {{.PKG}}

  cover:
    desc: Visualize test coverage
    deps: [test]
    cmds:
      - go tool cover -html={{.DIST}}/coverage.txt

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.DIST}}

  build:
    desc: Build all cmds
    deps: [dist]
    cmds:
      - go build -o {{.DIST}}/{{.APP}} cmd/{{.APP}}/*.go
      - go build -o {{.DIST}}/{{.APP}}d cmd/{{.APP}}d/*.go

  lint:
    desc: Runs golint
    cmds:
      - golangci-lint -v run

  snapshot:
    desc: Build a snapshot
    deps: [test, lint]
    cmds:
      - goreleaser --debug release --snapshot --rm-dist
