name: build

on:
  push

permissions:
  contents: read

jobs:
  ci:
    uses: bzimmer/actions/.github/workflows/build.yaml@main
    with:
      skipTests: false
      skipBuilds: false

  vuln:
    uses: bzimmer/actions/.github/workflows/vuln.yaml@main

  regression:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: install task
        uses: arduino/setup-task@v1

      - name: run regression
        run: task test:regression -- 20
