name: build

on:
  push

permissions:
  contents: read

jobs:
  build:
    uses: bzimmer/actions/.github/workflows/build.yaml@main
    with:
      skipBuild: false
      skipCoverage: false

  vuln:
    uses: bzimmer/actions/.github/workflows/vuln.yaml@main

  mkdocs:
    uses: bzimmer/actions/.github/workflows/mkdocs.yaml@main
    permissions:
      contents: write

  regression:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: install task
        uses: arduino/setup-task@v1

      - name: install dependencies
        run: |
          sudo add-apt-repository ppa:mithrandie/csvq
          sudo apt-get update
          sudo apt-get install csvq fd-find zsh jq

          mkdir -p ${HOME}/.local/bin
          ln -s $(which fdfind) ${HOME}/.local/bin/fd
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: run regression
        run: task test:regression -- 20
