# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - name: install go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
      - name: extract go version
        id: go-version
        run: echo "version=$(go list -m -f '{{.GoVersion}}')" >> "$GITHUB_OUTPUT"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg GO_VERSION=${{ steps.go-version.outputs.version }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
